NewProjected/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using NewProjected.Models;

namespace NewProjected.Controllers
{
    public class VehiclesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Vehicles
        public ActionResult Index()
        {
            return View(db.Vehicles.ToList());
        }
        
        public ActionResult PaymentDetails(int id)
        {
            ViewBag.id = id;
            ViewBag.status = db.Order.Where(l => l.OrderID == id).Select(i => i.Status).FirstOrDefault();
            ViewBag.ordertotal = db.Order.Where(l => l.OrderID == id).Select(i => i.OrderTotal).FirstOrDefault();
            ViewBag.UserName = db.Order.Where(l => l.OrderID == id).Select(i => i.UserID).FirstOrDefault();

            Payments payment = new Payments();
            payment.orderID = id;
            payment.AmountPayed= db.Order.Where(l => l.OrderID == id).Select(i => i.OrderTotal).FirstOrDefault();
            return View(payment);
        }

        [Authorize]
        public ActionResult BookingIndex()
        {
            return View(db.BookingItems.ToList().Where(l=>l.UserID==User.Identity.Name&&l.OrderID==0&& (l.CakeMessage == string.Empty || l.CakeMessage == null)));
        } 
        [Authorize]
        public ActionResult BookingCakeIndex()
        {
            var backeries = db.Backeries.ToList();
            var bookingCakes = new List<BookingItems>();
            foreach (var item in backeries)
            {
                var bookedItem = new BookingItems();
                bookedItem = db.BookingItems.Where(l => l.ItemId == item.CakeID && l.ItemName == item.Flavour&&l.OrderID==0).FirstOrDefault();
                if (bookedItem!=null) 
                {
                    bookingCakes.Add(bookedItem);
                }
            }
            return View(bookingCakes);
        }
        [Authorize]
        [ChildActionOnly]
        public ActionResult CakeDetails(int id)
        {
            var backeries = db.Backeries.ToList();
            var bookingCakes = new List<BookingItems>();
            foreach (var item in backeries)
            {
                var bookedItem = new BookingItems();
                bookedItem = db.BookingItems.Where(l => l.ItemId == item.CakeID && l.ItemName == item.Flavour&&l.OrderID==id).FirstOrDefault();
                if (bookedItem!=null) 
                {
                    bookingCakes.Add(bookedItem);
                }
            }
            return PartialView(bookingCakes);
        }

        [Authorize]
        [ChildActionOnly]
        public ActionResult BookingItems(int id)
        {
            ViewBag.id = id;
            ViewBag.status = db.Order.Where(l => l.OrderID == id).Select(i => i.Status).FirstOrDefault();

            var backeries = db.Backeries.ToList();
            var bookingCakes = db.BookingItems.Where(l=>(l.CakeMessage==string.Empty|| l.CakeMessage == null )&& l.OrderID==id).ToList();
           
            return PartialView(bookingCakes);
        }
        [Authorize]
        public ActionResult BookedItems(int id)
        {
            ViewBag.id = id;
            ViewBag.status = db.Order.Where(l => l.OrderID == id).Select(i => i.Status).FirstOrDefault();

            var backeries = db.Backeries.ToList();
            var bookingCakes = new List<BookingItems>();
            foreach (var item in backeries)
            {
                var bookedItem = new BookingItems();
                bookedItem = db.BookingItems.Where(l => l.ItemId != item.CakeID && l.ItemName != item.Flavour && l.OrderID != id).FirstOrDefault();
                bookingCakes.Add(bookedItem);
            }
            return View(bookingCakes);
        }

        [Authorize]
        public ActionResult OrderDetails()
        {
            var list = db.Order.ToList();

            if (!User.IsInRole("Admin")) 
            {
                list = list.Where(l => l.UserID == User.Identity.Name).ToList();
            }
            return View(list);
        }


        [Authorize]
        public ActionResult NewOrder()
        {
            var newOrder = new Order();
            newOrder.UserID = User.Identity.Name;
            newOrder.Status = "Waiting for Approval";
            newOrder.OrderTotal = db.BookingItems.Where(l => l.UserID == User.Identity.Name && l.OrderID == 0).Select(l => l.Rental).Sum();
            db.Order.Add(newOrder);
            db.SaveChanges();

            var bookings = db.BookingItems.Where(o => o.UserID == User.Identity.Name && o.OrderID == 0);
            foreach (var item in bookings)
            {
                item.OrderID = newOrder.OrderID;
                db.Entry(item).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("OrderDetails");
        }

        // GET: Vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicles vehicles = db.Vehicles.Find(id);
            if (vehicles == null)
            {
                return HttpNotFound();
            }
            return View(vehicles);
        }

        // GET: Vehicles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Pic")]Vehicles vehicles)
        {
            if (ModelState.IsValid)
            {
                byte[] Pic = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Pic"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        Pic = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }
                vehicles.Pic = Pic;
                vehicles.Deposit = vehicles.PricePerDay / 2;
                db.Vehicles.Add(vehicles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicles);
        }
        public FileContentResult UserPhotos(int vehicleId)
        {
            if (vehicleId == 0)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");

            }
            else
            {
                var pic = db.Vehicles.Where(k => k.VehicleID == vehicleId).Select(k => k.Pic).FirstOrDefault();
                return new FileContentResult(pic, "image/jpeg");

            }
        }

        // GET: Vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicles vehicles = db.Vehicles.Find(id);
            if (vehicles == null)
            {
                return HttpNotFound();
            }
            return View(vehicles);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleID,CarName,Model,PassangerNum,Colour,numberPlate,Deposit,PricePerDay,Pic")] Vehicles vehicles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicles);
        }

        // GET: Vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicles vehicles = db.Vehicles.Find(id);
            if (vehicles == null)
            {
                return HttpNotFound();
            }
            return View(vehicles);
        }

        public ActionResult Approve(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var Order = db.Order.Where(l=>l.OrderID==id).FirstOrDefault();
            Order.Status = "Approved";
            db.Entry(Order).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("OrderDetails");
        }
        public ActionResult Decline(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var Order = db.Order.Where(l=>l.OrderID==id).FirstOrDefault();
            Order.Status = "Declined";
            db.Entry(Order).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("OrderDetails");
        }

NewProjected/Views/Vehicles/BookedItems.cshtml
@model IEnumerable<NewProjected.Models.BookingItems>

@{
    ViewBag.Title = "Index";
}

<h2>Booked Facilities</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deposit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rental)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <th>
        @Html.DisplayFor(model => item.ItemName)
    </th>
    <th>
        @Html.DisplayFor(model => item.PickupDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.ReturnDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.Deposit)
    </th>
    <th>
        @Html.DisplayFor(model => item.Rental)
    </th>
</tr>
}
</table>

NewProjected/Views/Vehicles/BookingCakeIndex.cshtml
@model IEnumerable<NewProjected.Models.BookingItems>

@{
    ViewBag.Title = "Index";
}

<h2>Added Cakes</h2>
@if (Model.Count()>0) 
{
<button>
    <a href="@Url.Action("NewOrder", "Vehicles")">
       Place Order
    </a>
</button>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.CakeMessage)
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <th>
        @Html.DisplayFor(model => item.ItemName)
    </th>
    <th>
        @Html.DisplayFor(model => item.PickupDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.CakeMessage)
    </th>
    <th>
        @Html.DisplayFor(model => item.Rental)
    </th>
    
</tr>
}
</table>

NewProjected/Views/Vehicles/BookingIndex.cshtml
@model IEnumerable<NewProjected.Models.BookingItems>

@{
    ViewBag.Title = "Index";
}

<h2>Booked Facilities</h2>
@if (Model.Count()>0) 
{
<button>
    <a href="@Url.Action("NewOrder", "Vehicles")">
       Place Order
    </a>
</button>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Item Name")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deposit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rental)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <th>
        @Html.DisplayFor(model => item.ItemName)
    </th>
    <th>
        @Html.DisplayFor(model => item.PickupDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.ReturnDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.Deposit)
    </th>
    <th>
        @Html.DisplayFor(model => item.Rental)
    </th>
    <th>
        @Html.DisplayFor(model => item.Quantity)
    </th>
</tr>
}
</table>

NewProjected/Views/Vehicles/BookingItems.cshtml
@model IEnumerable<NewProjected.Models.BookingItems>

@{
    ViewBag.Title = "Index";
}

<h2>Booked Facilities</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deposit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rental)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <th>
        @Html.DisplayFor(model => item.ItemName)
    </th>
    <th>
        @Html.DisplayFor(model => item.PickupDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.ReturnDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.Deposit)
    </th>
    <th>
        @Html.DisplayFor(model => item.Rental)
    </th>
</tr>
}
</table>

NewProjected/Views/Vehicles/CakeDetails.cshtml
@model IEnumerable<NewProjected.Models.BookingItems>


<h2>Cakes</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.CakeMessage)
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <th>
        @Html.DisplayFor(model => item.ItemName)
    </th>
    <th>
        @Html.DisplayFor(model => item.PickupDate)
    </th>
    <th>
        @Html.DisplayFor(model => item.CakeMessage)
    </th>
    <th>
        @Html.DisplayFor(model => item.Rental)
    </th>

</tr>
    }
</table>

NewProjected/Views/Vehicles/Create.cshtml
@model NewProjected.Models.Vehicles

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Vehicles", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Vehicles</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CarName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CarName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PassangerNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PassangerNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PassangerNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.numberPlate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.numberPlate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numberPlate, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Pic, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <h4>Select Picture</h4>
            <input type="file" name="Pic" id="Pic" accept=".jpg" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewProjected/Views/Vehicles/Delete.cshtml
@model NewProjected.Models.Vehicles

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassangerNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassangerNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numberPlate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numberPlate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NewProjected/Views/Vehicles/Details.cshtml
@model NewProjected.Models.Vehicles

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassangerNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassangerNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numberPlate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numberPlate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pic)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NewProjected/Views/Vehicles/Index.cshtml
@model IEnumerable<NewProjected.Models.Vehicles>

@{
    ViewBag.Title = "Vehicle Booking";
}

    <style>
        div.gallery {
            margin: 5px;
            border: 1px solid #ccc;
            float: left;
            width:230;
            background-color:mediumpurple;
        }

            div.gallery:hover {
                border: 1px solid #777;
            }

        div.desc {
            text-align: left;
        }
    </style>

<h2>Vehicle Booking </h2>



<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            
            
            <div class="gallery">
                <a target="_blank" href="img_5terre.jpg">


                    @{
                        var base64 = Convert.ToBase64String(item.Pic);
                        var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                    }
                    <a href='@Url.Action("Details", new { id = item.VehicleID })'>
                        <img src='@imgsrc' height="150" width="230" />
                    </a>

                </a>
                <div class="desc">Vehicle name :  @Html.DisplayFor(modelItem => item.CarName)</div>
                <div class="desc">Deposit amount : R @Html.DisplayFor(modelItem => item.Deposit)</div>
                <div class="desc">Cost per day : R @Html.DisplayFor(modelItem => item.PricePerDay)</div>
                <div class="desc">Max number of passangers : @Html.DisplayFor(modelItem => item.PassangerNum)</div>
                <div class="desc">Number plate :  @Html.DisplayFor(modelItem => item.numberPlate)</div>
                <div class="desc">Quantity :  @Html.DisplayFor(modelItem => item.Quantity)</div>

                <button >
                    <a href="@Url.Action("NewBooking", "Tents", new { itemId = item.VehicleID, itemName = item.CarName })">
                        Add Booking
                    </a>
                    @*@Html.ActionLink("Make a booking", "NewBooking", "Tents", new { itemId = item.VehicleID, itemName = item.CarName })*@
                </button>
            </div>
        </tr>
    }

</table>

NewProjected/Views/Vehicles/OrderDetails.cshtml
@model IEnumerable<NewProjected.Models.Order>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
@{
    ViewBag.Title = "Order Details";
}

    <h2>My Order Details</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>

        @if (User.IsInRole("Admin"))
        {
    <th>
        @Html.DisplayName("User Email") 
    </th>}
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.OrderID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OrderTotal)
    </td>
    @if (User.IsInRole("Admin"))
    {
        <td>
         @Html.DisplayFor(model => item.UserID)
        </td>
    }
    <td>
@Html.DisplayName(item.Status) 

    </td>

    <td>
        <a href="@Url.Action("PaymentDetails", "Vehicles", new {  id = item.OrderID  })">
            <button>
              View Order Details
            </button>
        </a>
    </td>

</tr>
}

</table>

NewProjected/Views/Vehicles/PaymentDetails.cshtml
@model  NewProjected.Models.Payments

<h2>Order Number : @ViewBag.id</h2>
<h2>Order Status : @ViewBag.status</h2>
<h2>Order Total : R @ViewBag.ordertotal</h2>

<p>

    <button>
        <a href="@Url.Action("OrderDetails", "Vehicles")">
            Back to Order list
        </a>
    </button>
    @if (ViewBag.status == "Waiting for Approval" && User.IsInRole("Admin"))
    {
<a href="@Url.Action("Approve", "Vehicles", new { id = ViewBag.id })">
    <button>
        Approve Order
    </button>
</a>
    <a href="@Url.Action("Decline", "Vehicles", new { id = ViewBag.id })">
    <button>
        Decline Order
    </button>
</a>}
   

</p>
<div style="background-color: rosybrown; border:dashed;">
    @{ Html.RenderAction("BookingItems", "Vehicles", new { id = ViewBag.id }); }

</div>
<hr />
<div style="background-color: rosybrown; border:dashed;">
    @{ Html.RenderAction("CakeDetails", "Vehicles", new { id = ViewBag.id }); }

</div>
@using (Html.BeginForm("Create", "Payment", FormMethod.Post))
{
@Html.AntiForgeryToken()
<div class="form-horizontal">
    @*<h4>New Payment</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.orderID)

<div class="form-group">
    <h3>Total Amount : R @ViewBag.ordertotal</h3>

</div>

    @if (ViewBag.status=="Approved" && ViewBag.UserName==User.Identity.Name)
    {
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value=" Proceed with Payment" class="btn btn-success" />
    </div>
</div>
    }
</div>
}